Task 1 - User Model and Tests
TheDevJoao/peeper-rails pull request #2
Opened 2023-02-01 23:35 UTC by TheDevJoao

Created a user model class and its RSpec tests.

2023-02-02 15:37 UTC, bedreski approved these changes
Nice regex here, i was testing and it looks like work perfectly :+1: 
Also, the validations are well described in the code

2023-02-02 15:55 UTC, bedreski commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Here, tests was working until I try to test via Rails Console. Because of user migration isn't in the project, I can't execute the project locally and correctly. I tried to execute 'rails db:reset' command, and after that even in tests, it can't find the 'users' table. I think adding the migration in the Github project can solve all this. Also, with the migration, I will be able to verify tests better :+1:

2023-02-02 15:56 UTC, bedreski commented on spec/factories/users.rb
> +FactoryBot.define do
After adding the user migration, I will can verify this better too :handshake:

2023-02-02 16:00 UTC, bedreski requested changes
[post-it] user migration file

2023-02-02 18:01 UTC, TheDevJoao commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
Woops, just commited the migration and schema files that were left out. Thanks for pointing that out!

2023-02-02 18:03 UTC, TheDevJoao commented on spec/factories/users.rb
> +FactoryBot.define do
Added them now, sorry about that. Let me know what you think whenever you can :D

2023-02-02 22:47 UTC, bedreski commented on db/migrate/20230202175622_users.rb
> +class Users < ActiveRecord::Migration[7.0]
Thanks! I will check this out :+1:

2023-02-03 17:01 UTC, bedreski approved these changes

2023-02-06 20:25 UTC, merged